[env]
G_PLUS_PLUS = "g++-13"

[tasks.floyd-build]
command = "${G_PLUS_PLUS}"
args = ["../multi_agent_path_finding/floyd.cpp", "-o", "bin/floyd.out", "-std=c++17", "-O0", "-Xlinker", "-ld_classic"]

# Apple uses their new linker in macOS Sonoma 14... unfortuantely the linker crashes in a lot of cases (see https://developer.apple.com/forums/thread/737707)
# So we use the old linker for now. ["-Xlinker", "-ld_classic"]

[tasks.floyd-release-build]
command = "${G_PLUS_PLUS}"
args = ["../multi_agent_path_finding/floyd.cpp", "-o", "bin/floyd.out", "-std=c++17", "-O3", "-Xlinker", "-ld_classic"]

[tasks.optimization-build]
command = "${G_PLUS_PLUS}"
args = ["../multi_agent_path_finding/multi-objective-agent.cpp", "-o", "bin/optimization.out", "-std=c++17", "-O0", "-Xlinker", "-ld_classic"]

[tasks.optimization-release-build]
command = "${G_PLUS_PLUS}"
args = ["../multi_agent_path_finding/multi-objective-agent.cpp", "-o", "bin/optimization.out", "-std=c++17", "-O3", "-Xlinker", "-ld_classic"]

[tasks.entry-run]
command = "cargo"
args = ["run"]

[tasks.entry-build]
command = "cargo"
args = ["build"]

[tasks.entry-release-build]
command = "cargo"
args = ["build", "--release"]

[tasks.entry-release-run]
command = "cargo"
args = ["run", "--release"]

[tasks.run]
dependencies = [
    "floyd-build",
    "optimization-build",
    "entry-run",
]

[tasks.build]
dependencies = [
    "floyd-build",
    "optimization-build",
    "entry-build",
]

[tasks.release]
dependencies = [
    "floyd-release-build",
    "optimization-release-build",
    "entry-release-run",
]
